[package]
name = "mts-esp-client-sys"
description = "MTS-ESP client bindings"
version = "0.1.0"
edition = "2021"
authors = ["Joakim Frosteg√•rd <joakim.frostegard@gmail.com>"]

[dependencies]

[build-dependencies]
cc = "1.0"
